# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestDownloaddata():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_downloaddata(self):
    self.driver.get("https://www.powercor.com.au/")
    self.driver.set_window_size(1280, 720)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.vars["win6248"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6248"])
    self.driver.find_element(By.ID, "j_id0:SiteTemplate:j_id297:loginComponent:loginForm:password").send_keys("***REMOVED***")
    self.driver.find_element(By.ID, "j_id0:SiteTemplate:j_id297:loginComponent:loginForm:username").send_keys("***REMOVED***")
    self.driver.find_element(By.ID, "j_id0:SiteTemplate:j_id297:loginComponent:loginForm:username").click()
    self.driver.find_element(By.ID, "j_id0:SiteTemplate:j_id297:loginComponent:loginForm:password").click()
    self.driver.find_element(By.ID, "j_id0:SiteTemplate:j_id297:loginComponent:loginForm:loginButtonAccountPage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-12 > .btn-primary").click()
    self.driver.find_element(By.ID, "reportType").click()
    dropdown = self.driver.find_element(By.ID, "reportType")
    dropdown.find_element(By.XPATH, "//option[. = 'Detailed Report (CSV)']").click()
    self.driver.find_element(By.ID, "reportType").click()
    self.driver.find_element(By.NAME, "j_id0:SiteTemplate:j_id158:j_id235").click()
  
